# Generated by Django 4.2 on 2023-04-26 05:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("onTheRoof", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogposts",
            name="filter",
        ),
    ]
