# Generated by Django 4.2 on 2023-04-26 07:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("onTheRoof", "0002_remove_blogposts_filter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="avatar",
            old_name="img_src",
            new_name="avatar",
        ),
    ]
